-- Create Stadiums table
CREATE TABLE stadiums (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name VARCHAR2(255),
  city VARCHAR2(255),
  capacity NUMBER,
  PRIMARY KEY (id)
);

-- Create Teams table
CREATE TABLE teams (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name VARCHAR2(255),
  founded DATE,
  stadium_id NUMBER,
  manager_name VARCHAR2(255),
  PRIMARY KEY (id),
  FOREIGN KEY (stadium_id) REFERENCES stadiums(id)
);

-- Create Matches table
CREATE TABLE matches (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  match_date DATE,
  home_team_score NUMBER,
  away_team_score NUMBER,
  referee_name VARCHAR2(255),
  match_week NUMBER,
  home_team_id NUMBER,
  away_team_id NUMBER,
  stadium_id NUMBER,
  PRIMARY KEY (id),
  FOREIGN KEY (stadium_id) REFERENCES stadiums(id),
  FOREIGN KEY (home_team_id) REFERENCES teams(id),
  FOREIGN KEY (away_team_id) REFERENCES teams(id)
);

-- Create Tickets table
CREATE TABLE tickets (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  sector VARCHAR2(255),
  price NUMBER,
  quantity NUMBER,
  match_id NUMBER,
  PRIMARY KEY (id),
  FOREIGN KEY (match_id) REFERENCES matches(id)
);

-- Create Members table
CREATE TABLE members (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name VARCHAR2(255),
  surname VARCHAR2(255),
  dob DATE,
  salary NUMBER,
  nationality VARCHAR2(255),
  team_id NUMBER,
  PRIMARY KEY (id),
  FOREIGN KEY (team_id) REFERENCES teams(id)
);